DROP TABLE IF EXISTS habit;
CREATE TABLE habit(
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    habit_frequency VARCHAR(255) NOT NULL,
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    end_date TIMESTAMP DEFAULT DATEADD(YEAR, 1, CURRENT_TIMESTAMP()),
    reminder BOOLEAN DEFAULT FALSE
);